# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoQuiz < Formula
  desc "Quiz web server"
  homepage "https://go-quiz"
  version "0.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hansbringert/go-quiz/releases/download/v0.0.0/go-quiz_macOS_64-bit.zip"
    sha256 "99e3ab45756d7edee8768a6cbd2e05eda64fee231d8c27a2429b7300abf5249c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hansbringert/go-quiz/releases/download/v0.0.0/go-quiz_Tux_64-bit.zip"
    sha256 "c3b67190ec71fa28f01da6d55cb7871a44c571af3c25429ead2c3d0403e0596f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hansbringert/go-quiz/releases/download/v0.0.0/go-quiz_Tux_arm64.zip"
    sha256 "a4c5dbe336421b631c4be7b06938549f3a940fb4a2ea21f81f23e8c7532ce907"
  end

  def install
    bin.install "go-quiz"
  end
end
