# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoQuiz < Formula
  desc "Quiz web server"
  homepage "https://go-quiz"
  version "0.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hansbringert/go-quiz/releases/download/v0.0.0/go-quiz_macOS_64-bit.zip"
    sha256 "514518217c7f3fecb038cc3dcf3a0e41ef17d67133ebda2cdbbaa7b9babeacd7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hansbringert/go-quiz/releases/download/v0.0.0/go-quiz_Tux_64-bit.zip"
    sha256 "48408a59e032253cf6a6d46c9a8ee17566c0e1867563edbe9e938e267f3ad338"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hansbringert/go-quiz/releases/download/v0.0.0/go-quiz_Tux_arm64.zip"
    sha256 "2cf754d6283540cd0665ad8cac6edb4586dec5cdb80eba614ef259be02c1798a"
  end

  def install
    bin.install "go-quiz"
  end
end
