# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorld < Formula
  desc "Hello World"
  homepage "https://hello"
  version "0.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/hello-world/0.0.0/hello-world_macOS_64-bit.zip"
    sha256 "9e993786104427c82ed68ed85dff30f349fd20a8115f242bd8605802762fdb53"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/hello-world/0.0.0/hello-world_Tux_64-bit.zip"
    sha256 "da133fcf38379e04290335628e327a161b64fb2b788e70ad273f077717594e9c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://im-saas-build-public-artifacts.s3-eu-west-1.amazonaws.com/tools/hello-world/0.0.0/hello-world_Tux_arm64.zip"
    sha256 "93695f6aa1bed02e76a33a2f595abc5524ab3f5136790c2166366d50040e9693"
  end

  def install
    bin.install "hello-world"
  end
end
