# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorld < Formula
  desc "Hello World"
  homepage "https://hello"
  version "0.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hansbringert/hello-world_macOS_64-bit.zip/releases/download/v0.0.0/hello-world_macOS_64-bit.zip_macOS_64-bit.zip"
    sha256 "00bc71a1a3270e18ec1b40bd46f2cb432ad11fe5018ff89a361fc459da37fb0c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hansbringert/hello-world_Tux_64-bit.zip/releases/download/v0.0.0/hello-world_Tux_64-bit.zip_macOS_64-bit.zip"
    sha256 "808bf53dd307c2f5d7847e8387966376e7e74812eb749b5c745d5af1482e41f0"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hansbringert/hello-world_Tux_arm64.zip/releases/download/v0.0.0/hello-world_Tux_arm64.zip_macOS_64-bit.zip"
    sha256 "d27a61fedef819c0cd6d1ca6d1464e0d7ca47919b3f5ca6d289d6872fdffb7fd"
  end

  def install
    bin.install "hello-world"
  end
end
